
name: Trigger auto deployment for kbfmatcher-dev

# When this action will be executed
on:
  push:
    branches: 
      [ dev ]
    paths:
    - '**'
    - '.github/workflows/deployment.yml'

  # Allow manual trigger 
  workflow_dispatch:

permissions:
  id-token: write
  contents: read      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login with Client Secret
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CAM_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CAM_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CAM_AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.CAM_AZURE_CLIENT_SECRET }} 

      - name: Log in to Azure Container Registry (ACR)
        run: |
          az acr login --name ksmacr

      # Build and Push Docker Image
      - name: Build and Push Image
        run: |
          docker build --no-cache -t ksmacr.azurecr.io/kbfmatcher-dev:${{ github.sha }} ./
          docker push ksmacr.azurecr.io/kbfmatcher-dev:${{ github.sha }}

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
            --name kbfmatcher-dev \
            --resource-group KSM_Teaching_RG \
            --image ksmacr.azurecr.io/kbfmatcher-dev:${{ github.sha }} \
